apiVersion: v1
kind: Service
metadata:
  name: influxdb-rest-service
  namespace: extensions
  labels:
    app: influxdb-rest
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    app: influxdb-rest
