######################################################################
# Copyright (c) 2020 Bosch.IO GmbH [and others]
#
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
########################################################################
---
apiVersion: v2
name: kuksa-cloud
description: A Helm chart for deploying the core parts of the Eclipse Kuksa cloud to a Kubernetes instance. The Eclipse Kuksa cloud consists of the following parts Eclipse Hono, Eclipse hawkBit, Keycloak, InfluxDb, Kuksa Hono-to-InfluxDb-Connector.

home: https://eclipse.org/kuksa
keywords: 
    - IoT
    - Kuksa
    - Connected Vehicle
    - Connected Driving
type: application

version: 0.0.1
apiVersion: v2
appVersion: 0.2.0
maintainers:
    - name: eriksven
      email: svenerik.jeroschewski@bosch.io

dependencies:
    - name: hono
      version: ~1.3.19
      repository: https://eclipse.org/packages/charts
      condition: components.hono.enabled
    - name: influxdb
      version: ~4.4.8
      repository: https://helm.influxdata.com/
      condition: components.influxdb.enabled
    - name: hawkbit
      version: ~1.2.2
      repository: https://eclipse.org/packages/charts
      condition: components.hawkbit.enabled
    - name: keycloak
      version: ~8.0.0
      repository: https://codecentric.github.io/helm-charts
      condition: components.keycloak.enabled
    - name: ambassador
      version: ~6.4.5
      repository: https://www.getambassador.io
      condition: components.ambassador.enabled
#    - name: cert-manager
#      version: ~0.15.2
#      repository: https://charts.jetstack.io
#      condition: components.cert-manager.enabled
   