keycloak:
  username: admin
  password: admin
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    path: /auth/
  extraVolumes: |
    - name: configuration
      configMap:
        name: keycloak-configuration
  extraVolumeMounts: |
    - name: configuration
      mountPath: "/opt/jboss/keycloak/kuksa/"
      readOnly: true
  extraArgs: "-Dkeycloak.import=/opt/jboss/keycloak/kuksa/kuksa-realm.json"
